// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

/**
 * @title FaceVerifier
 * @notice On-chain Groth16 ZK-SNARK verifier for V-FACE face proofs.
 *
 * This contract is generated from FaceProof.circom via:
 *   snarkjs zkey export solidityverifier FaceProof_final.zkey FaceVerifier.sol
 *
 * The verification key below is a PLACEHOLDER.
 * Replace with actual values from your trusted setup ceremony output.
 *
 * Verification key structure (Groth16, BN128 curve):
 *   - alpha1, beta2, gamma2, delta2  : pairing parameters
 *   - IC[]                           : one point per public signal + 1
 */
interface IVerifier {
    function verifyFaceProof(
        uint[2] calldata a,
        uint[2][2] calldata b,
        uint[2] calldata c,
        uint[3] calldata input  // [commitment, threshold_sq, valid]
    ) external view returns (bool);
}

contract FaceVerifier {
    // ── Verification Key (replace after trusted setup) ─────────────────────
    uint256 constant ALPHA_X = 0; // placeholder
    uint256 constant ALPHA_Y = 0;

    // IC[0] is the constant term; IC[i] corresponds to publicSignals[i-1]
    // Public signals: [commitment, threshold_sq, valid]
    uint256[4][2] IC; // 3 signals + 1 constant = 4 points

    // ── Events ──────────────────────────────────────────────────────────────
    event ProofVerified(address indexed verifier, bytes32 commitment, bool valid);

    /**
     * @notice Verify a Groth16 ZK proof from the V-FACE SDK.
     * @param a  Proof point A (G1)
     * @param b  Proof point B (G2)
     * @param c  Proof point C (G1)
     * @param input Public signals: [commitment, threshold_sq, valid]
     * @return True if proof is valid
     */
    function verifyFaceProof(
        uint[2] calldata a,
        uint[2][2] calldata b,
        uint[2] calldata c,
        uint[3] calldata input
    ) external returns (bool) {
        bool result = _groth16Verify(a, b, c, input);
        emit ProofVerified(msg.sender, bytes32(input[0]), result);
        return result;
    }

    /**
     * @dev Core Groth16 pairing verification.
     *      Generated by snarkjs — do not modify manually.
     *      Replaced at deploy time with actual verification key.
     */
    function _groth16Verify(
        uint[2] calldata a,
        uint[2][2] calldata b,
        uint[2] calldata c,
        uint[3] calldata input
    ) internal view returns (bool) {
        // Pairing check: e(A, B) = e(alpha, beta) * e(vk_x, gamma) * e(C, delta)
        // vk_x = IC[0] + sum(IC[i+1] * input[i])
        //
        // Implementation: use the BN128 precompiles at addresses 0x06, 0x07, 0x08
        // This body is auto-generated by snarkjs and replaces this placeholder.

        // PLACEHOLDER: always returns false until real VK is inserted
        return false;
    }
}

/**
 * @title VFaceZKRegistry
 * @notice Extends VFaceRegistry with ZK-proof-based identity anchoring.
 *         Identities are registered by proof commitment — no biometric data on-chain.
 */
contract VFaceZKRegistry {
    IVerifier public immutable verifier;

    struct ZKIdentity {
        bytes32 commitment;   // Poseidon(embedding) — not reversible
        address wallet;
        uint256 registeredAt;
        bool    active;
    }

    mapping(bytes32 => ZKIdentity) public identities;  // commitment → identity
    mapping(address => bytes32)    public walletCommitment;

    event ZKIdentityRegistered(address indexed wallet, bytes32 commitment);
    event ZKIdentityRevoked(address indexed wallet, bytes32 commitment);

    constructor(address _verifier) {
        verifier = IVerifier(_verifier);
    }

    /**
     * @notice Register a face identity using a ZK proof.
     *         No biometric data is sent — only a cryptographic commitment.
     *
     * @param a, b, c  Groth16 proof points
     * @param publicSignals [commitment, threshold_sq, valid]
     */
    function registerWithProof(
        uint[2] calldata a,
        uint[2][2] calldata b,
        uint[2] calldata c,
        uint[3] calldata publicSignals
    ) external {
        require(publicSignals[2] == 1, "ZK: proof invalid (valid != 1)");

        bool ok = verifier.verifyFaceProof(a, b, c, publicSignals);
        require(ok, "ZK: Groth16 verification failed");

        bytes32 commitment = bytes32(publicSignals[0]);
        require(identities[commitment].registeredAt == 0, "ZK: already registered");
        require(walletCommitment[msg.sender] == bytes32(0), "ZK: wallet already has identity");

        identities[commitment] = ZKIdentity({
            commitment:    commitment,
            wallet:        msg.sender,
            registeredAt:  block.timestamp,
            active:        true
        });
        walletCommitment[msg.sender] = commitment;

        emit ZKIdentityRegistered(msg.sender, commitment);
    }

    function revokeIdentity() external {
        bytes32 c = walletCommitment[msg.sender];
        require(c != bytes32(0), "ZK: no identity found");
        identities[c].active = false;
        emit ZKIdentityRevoked(msg.sender, c);
    }

    function isRegistered(bytes32 commitment) external view returns (bool) {
        return identities[commitment].active;
    }
}
