/**
 * V-FACE ZK-SNARK Helpers
 * Uses snarkjs + Groth16 proving system
 *
 * Setup flow (run ONCE, offline, by trusted party):
 *   1. npx snarkjs groth16 setup FaceProof.r1cs pot14_final.ptau FaceProof_0000.zkey
 *   2. npx snarkjs zkey contribute FaceProof_0000.zkey FaceProof_final.zkey
 *   3. npx snarkjs zkey export verificationkey FaceProof_final.zkey verification_key.json
 *   4. npx snarkjs zkey export solidityverifier FaceProof_final.zkey FaceVerifier.sol
 *
 * Runtime flow (per verification):
 *   generateProof(embedding) → { proof, publicSignals }
 *   verifyProof(proof, publicSignals) → boolean
 */

import * as snarkjs from 'snarkjs';

// Paths — in production, host these on a CDN or IPFS
const WASM_PATH   = '/circuits/FaceProof_js/FaceProof.wasm';
const ZKEY_PATH   = '/circuits/FaceProof_final.zkey';
const VKEY_PATH   = '/circuits/verification_key.json';

// Scaling factor — embedding floats → integers for circom
const SCALE = 10_000;
// Similarity threshold (cosine ≥ 0.75)
const THRESHOLD   = 0.75;
const THRESHOLD_SQ_SCALED = Math.round(THRESHOLD * THRESHOLD * SCALE * SCALE * 128);

/**
 * Scale a float embedding to integer array for circom.
 * MobileFaceNet outputs values roughly in [-1, 1].
 */
function scaleEmbedding(embedding) {
  return embedding.map(v => Math.round(v * SCALE).toString());
}

/**
 * Compute Poseidon commitment of scaled embedding.
 * This is the PUBLIC commitment stored on-chain / in Qdrant.
 * The raw embedding stays private.
 */
export async function computeCommitment(embedding) {
  const scaled = scaleEmbedding(embedding);
  // Use snarkjs poseidon directly (avoids separate dep)
  const { buildPoseidon } = await import('circomlibjs');
  const poseidon = await buildPoseidon();

  // Chain poseidon over chunks of 15
  let hash = poseidon(scaled.slice(0, 15));
  for (let i = 15; i < 128; i += 15) {
    const chunk = scaled.slice(i, i + 15);
    hash = poseidon([poseidon.F.toString(hash), ...chunk]);
  }
  return poseidon.F.toString(hash);
}

/**
 * Generate a ZK proof that "I know the registered embedding"
 * without revealing it.
 *
 * @param {number[]} embedding  — raw 128-d float array from MobileFaceNet
 * @returns {{ proof, publicSignals, commitment }}
 */
export async function generateProof(embedding) {
  const scaled     = scaleEmbedding(embedding);
  const commitment = await computeCommitment(embedding);

  const input = {
    embedding:    scaled,
    commitment:   commitment,
    threshold_sq: THRESHOLD_SQ_SCALED.toString(),
  };

  console.time('[ZK] Proof generation');
  const { proof, publicSignals } = await snarkjs.groth16.fullProve(
    input,
    WASM_PATH,
    ZKEY_PATH
  );
  console.timeEnd('[ZK] Proof generation');

  return { proof, publicSignals, commitment };
}

/**
 * Verify a ZK proof locally (client-side, no server needed).
 *
 * @param {object} proof
 * @param {string[]} publicSignals
 * @returns {boolean}
 */
export async function verifyProofLocal(proof, publicSignals) {
  const vKey = await fetch(VKEY_PATH).then(r => r.json());
  return snarkjs.groth16.verify(vKey, publicSignals, proof);
}

/**
 * Format proof for on-chain Solidity verifier (calldata).
 * Use with FaceVerifier.sol generated by snarkjs.
 */
export async function exportSolidityCalldata(proof, publicSignals) {
  return snarkjs.groth16.exportSolidityCallData(proof, publicSignals);
}

/**
 * Full ZK registration flow:
 *   1. Generate proof from embedding
 *   2. Return commitment (goes on-chain) + proof (verifiable by anyone)
 *
 * The server never receives the raw embedding — only the commitment.
 */
export async function zkRegister(embedding) {
  const { proof, publicSignals, commitment } = await generateProof(embedding);
  const valid = await verifyProofLocal(proof, publicSignals);

  if (!valid) {
    throw new Error('[ZK] Self-verification failed — proof is invalid');
  }

  return {
    commitment,        // Store on-chain & in Qdrant payload
    proof,             // Send to server for on-chain anchoring
    publicSignals,     // [commitment, threshold_sq, valid]
  };
}
